/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#0B1020',
        'background-secondary': '#111827',
        'background-tertiary': '#1A2238',
        surface: '#161D2E',
        card: '#1D263A',
        primary: '#B7FF3C',
        'primary-light': '#D8FF5A',
        'primary-dark': '#8FD600',
        secondary: '#3B82F6',
        'secondary-light': '#60A5FA',
        accent: '#00E5A8',
        'text-secondary': '#B5BDC9',
        'text-muted': '#7D8799',
        'text-disabled': '#556070',
        border: '#2A3448',
        divider: '#242E42',
        success: '#22C55E',
        warning: '#F59E0B',
        error: '#EF4444',
        info: '#3B82F6',
        calories: '#FF7A00',
        distance: '#3B82F6',
        duration: '#A855F7',
        steps: '#B7FF3C',
        'heart-rate': '#FF3B5C',
        speed: '#00D4FF',
        elevation: '#FACC15',
        gold: '#FFD54A',
        silver: '#C0C8D2',
        bronze: '#C97A3A',
      },
    },
  },
  plugins: [],
};
